# Generated by Django 6.0.2 on 2026-03-05 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '星期一'), (1, '星期二'), (2, '星期三'), (3, '星期四'), (4, '星期五'), (5, '星期六'), (6, '星期日')], help_text='星期幾 (0=星期一, 6=星期日)', unique=True)),
                ('has_class', models.BooleanField(default=True, help_text='該天是否有課')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '學校課表',
                'verbose_name_plural': '學校課表',
            },
        ),
        migrations.CreateModel(
            name='WarningAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_count', models.IntegerField(verbose_name='警告數量')),
                ('warning_types', models.CharField(help_text='逗號分隔的警告類型', max_length=500, verbose_name='警告類型列表')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='原始 API 響應')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='訪問 IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用戶代理')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='訪問時間')),
            ],
            options={
                'verbose_name': '警告讀取記錄',
                'verbose_name_plural': '警告讀取記錄',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_situation', models.CharField(blank=True, default='', max_length=255)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['-recorded_at'], name='weather_app_recorde_dd18e9_idx')],
            },
        ),
    ]
