# Generated by Django 6.0.2 on 2026-02-23 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of sessions for this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Session number (e.g., 1, 2, 3...)')),
                ('session_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='student_attendance.course')),
            ],
            options={
                'verbose_name_plural': 'Course Sessions',
                'db_table': 'course_session',
                'ordering': ['course', 'session_number'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('qr_code_data', models.TextField(blank=True, help_text='Data to be encoded in QR code')),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_code', to='student_attendance.coursesession')),
            ],
            options={
                'verbose_name_plural': 'Attendance Codes',
                'db_table': 'attendance_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Students',
                'db_table': 'student',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id'], name='student_student_97543b_idx'), models.Index(fields=['email'], name='student_email_e135f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], db_index=True, default='PRESENT', max_length=10)),
                ('check_in_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_attendance.attendancecode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='student_attendance.coursesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='student_attendance.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance Logs',
                'db_table': 'attendance_log',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
                'db_table': 'teacher',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher_id'], name='teacher_teacher_255d38_idx'), models.Index(fields=['email'], name='teacher_email_9e653f_idx')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='student_attendance.teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], db_index=True, default='MON', max_length=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_attendance.teacher')),
            ],
            options={
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['course', 'session_number'], name='course_sess_course__d4d1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['session_code'], name='course_sess_session_747192_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesession',
            index=models.Index(fields=['session_date'], name='course_sess_session_c5636c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursesession',
            unique_together={('course', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='attendancecode',
            index=models.Index(fields=['code'], name='attendance__code_05a40d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancecode',
            index=models.Index(fields=['expires_at'], name='attendance__expires_2c4ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student', 'session'], name='attendance__student_a6fa64_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['status', 'check_in_time'], name='attendance__status_133f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['session', 'status'], name='attendance__session_efa2f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('student', 'session')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_id'], name='course_course__708290_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_name'], name='course_course__75bc64_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'course'], name='attendance_student_a87d91_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['teacher', 'course'], name='attendance_teacher_d15d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['effective_day'], name='attendance_effecti_0bbc34_idx'),
        ),
    ]
