# Generated by Django 6.0.2 on 2026-02-23 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='student_student_97543b_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_email_e135f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='teacher_teacher_255d38_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacher',
            name='teacher_email_9e653f_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
