# Generated by Django 6.0.2 on 2026-02-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0002_remove_student_student_student_97543b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, help_text='Students enrolled in this course', related_name='enrolled_courses', to='student_attendance.student'),
        ),
    ]
